import Head from 'next/head';
import Hello from '../components/Hello';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hello />
    </>
  );
}
